# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node runtime ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: publish package
      run: npm publish --access=public

